---
swagger: "2.0"
info:
  description: "TheCoin simple broker services.  This sample API is an example of\
    \ how to setup the simplest low-volume exchange, when combined with the included\
    \ server code, without external dependencies"
  version: "0.1.0"
  title: "THE Coin Broker Sample"
  contact:
    email: "stephen.taylor.dev@gmail.com"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "broker-cad.appspot.com"
tags:
- name: "Sell"
  description: "The Coin exchange service.  This API allows clients to exchange THESE\
    \ for CAD"
- name: "Transfer"
  description: "Request the broker to make a transfer on the clients behalf"
- name: "Secure"
  description: "Functions to help secure an account"
schemes:
- "https"
consumes:
- "application/json"
produces:
- "application/json"
paths:
  /status:
    get:
      tags:
      - "Status"
      summary: "Gets the operating status of the broker"
      description: "Returns info like brokers address, available balance, etc (?)"
      operationId: "status"
      parameters: []
      responses:
        200:
          description: "Server status"
          schema:
            $ref: "#/definitions/BrokerStatus"
        405:
          description: "Server Error"
      x-swagger-router-controller: "Status"
  /referrers:
    get:
      tags:
      - "Referrers"
      summary: "Gets the validity of the passed referrer"
      description: "Returns a boolean indicating whether the passed referrer is valid"
      operationId: "referrerValid"
      parameters:
      - name: "referrer"
        in: "query"
        description: "Referrers ID.  This ID must have been previously registered\
          \ with the system"
        required: true
        type: "string"
      responses:
        200:
          description: "Id Valid"
          schema:
            $ref: "#/definitions/BoolResponse"
        405:
          description: "Server Error"
      x-swagger-router-controller: "Referrers"
    post:
      tags:
      - "Referrers"
      summary: "Register the referral of new account"
      description: "Returns a boolean indicating whether the passed referrer is valid"
      operationId: "referralCreate"
      parameters:
      - in: "body"
        name: "referral"
        description: "Set referal for new account"
        required: true
        schema:
          $ref: "#/definitions/NewAccountReferal"
      responses:
        200:
          description: "Referral success"
          schema:
            $ref: "#/definitions/BoolResponse"
        405:
          description: "Server Error"
      x-swagger-router-controller: "Referrers"
  /exchange/eTransfer:
    post:
      tags:
      - "eTransfer"
      summary: "Request eTransfer"
      description: "Called by the client to exchange coin for CAD and send via eTransfer"
      operationId: "eTransfer"
      parameters:
      - in: "body"
        name: "request"
        description: "Must contain a transfer to this brokers address, and an encrypted\
          \ ETransferPacket"
        required: true
        schema:
          $ref: "#/definitions/CertifiedTransfer"
      responses:
        200:
          description: "The response confirms to the user the order has been processed"
          schema:
            $ref: "#/definitions/CertifiedTransferResponse"
        405:
          description: "Invalid input"
      x-swagger-router-controller: "ETransfer"
  /exchange/eTransfer/code:
    put:
      tags:
      - "eTransfer"
      summary: "Required answer for eTransfer sent to this broker"
      description: "A code unique to the user that is required on all eTransfers sent\
        \ in to this broker"
      operationId: "eTransferInCode"
      parameters:
      - in: "body"
        name: "request"
        description: "Signed timestamp message"
        required: true
        schema:
          $ref: "#/definitions/SignedMessage"
      responses:
        200:
          description: "The requesters unique eTransfer code."
          schema:
            $ref: "#/definitions/eTransferCodeResponse"
        405:
          description: "Invalid input"
      x-swagger-router-controller: "ETransfer"
  /bills/payment:
    post:
      tags:
      - "Bill Payments"
      summary: "Bill Payment"
      description: "Called by the client to pay a bill with coin via a certified transfer"
      operationId: "billPayment"
      parameters:
      - in: "body"
        name: "request"
        description: "Must contain a transfer to this brokers address, and an encrypted\
          \ BillPayeePacket"
        required: true
        schema:
          $ref: "#/definitions/CertifiedTransfer"
      responses:
        200:
          description: "The response confirms to the user the order has been processed"
          schema:
            $ref: "#/definitions/CertifiedTransferResponse"
        405:
          description: "Invalid input"
      x-swagger-router-controller: "BillPayments"
  /transfer:
    post:
      tags:
      - "Transfer"
      summary: "Transfer to another The Coin account"
      description: "A client may request that the Broker initiate a transfer from\
        \ their account to another.  The transfer includes a fee paid to the broker\
        \ to cover the cost of the transfer.  This allows a user to operate on the\
        \ Ethereum blockchain without requiring their own ether"
      operationId: "transfer"
      parameters:
      - in: "body"
        name: "request"
        description: "A request appropriately filled out and signed as described in\
          \ the comments"
        required: true
        schema:
          $ref: "#/definitions/CertifiedTransferRequest"
      responses:
        200:
          description: "The response confirms to the user the order transfer is valid\
            \ and has been initiated"
          schema:
            $ref: "#/definitions/CertifiedTransferResponse"
        405:
          description: "Invalid input"
      x-swagger-router-controller: "Transfer"
  /secure/google:
    get:
      tags:
      - "Secure"
      summary: "Get the authorization URL to redirect the user to"
      operationId: "googleAuthUrl"
      parameters: []
      responses:
        200:
          description: "Google authorization URL"
          schema:
            $ref: "#/definitions/GoogleAuthUrl"
      x-swagger-router-controller: "Secure"
  /secure/google/list:
    put:
      tags:
      - "Secure"
      summary: "Get the listing of available accounts"
      operationId: "googleList"
      parameters:
      - in: "body"
        name: "token"
        required: true
        schema:
          $ref: "#/definitions/GoogleToken"
      responses:
        200:
          description: "Account successfully stored"
          schema:
            $ref: "#/definitions/GoogleListResult"
        405:
          description: "Permission Denied"
      x-swagger-router-controller: "Secure"
  /secure/google/put:
    put:
      tags:
      - "Secure"
      summary: "Store on google drive"
      operationId: "googlePut"
      parameters:
      - in: "body"
        name: "uploadPacket"
        required: true
        schema:
          $ref: "#/definitions/GooglePutRequest"
      responses:
        200:
          description: "Account successfully stored"
          schema:
            $ref: "#/definitions/BoolResponse"
        405:
          description: "Permission Denied"
      x-swagger-router-controller: "Secure"
  /secure/google/get:
    put:
      tags:
      - "Secure"
      summary: "Retrieve previously-stored file from google drive"
      operationId: "googleRetrieve"
      parameters:
      - in: "body"
        name: "token"
        required: true
        schema:
          $ref: "#/definitions/GoogleToken"
      responses:
        200:
          description: "Account successfully stored"
          schema:
            $ref: "#/definitions/GoogleGetResult"
        405:
          description: "Permission Denied"
      x-swagger-router-controller: "Secure"
  /newsletter/signup:
    put:
      tags:
      - "Newsletter"
      summary: "Register an email address for our newsletter."
      operationId: "newsletterSignup"
      parameters:
      - in: "body"
        name: "details"
        required: true
        schema:
          $ref: "#/definitions/SubscriptionDetails"
      responses:
        200:
          description: "Email successfully registered"
          schema:
            $ref: "#/definitions/BoolResponse"
        500:
          description: "Server Error"
      x-swagger-router-controller: "Newsletter"
  /newsletter/confirm:
    put:
      tags:
      - "Newsletter"
      summary: "Confirm email subscription."
      operationId: "newsletterConfirm"
      parameters:
      - in: "body"
        name: "details"
        required: true
        schema:
          $ref: "#/definitions/SubscriptionDetails"
      responses:
        200:
          description: "If found, returns new details merged with existing"
          schema:
            $ref: "#/definitions/SubscriptionDetails"
        400:
          description: "Not Found"
        500:
          description: "Server Error"
      x-swagger-router-controller: "Newsletter"
  /newsletter/details:
    get:
      tags:
      - "Newsletter"
      summary: "Get subscription details."
      operationId: "newsletterDetails"
      parameters:
      - name: "id"
        in: "query"
        required: true
        type: "string"
      responses:
        200:
          description: "If found, returns subscription details"
          schema:
            $ref: "#/definitions/SubscriptionDetails"
        400:
          description: "Not Found"
        500:
          description: "Server Error"
      x-swagger-router-controller: "Newsletter"
  /newsletter/unsubscribe:
    get:
      tags:
      - "Newsletter"
      summary: "Unsubscribe an email address from our newsletter."
      operationId: "newsletterUnsubscribe"
      parameters:
      - name: "id"
        in: "query"
        required: true
        type: "string"
      responses:
        200:
          description: "Email successfully registered"
          schema:
            $ref: "#/definitions/BoolResponse"
        400:
          description: "Not Found"
        500:
          description: "Server Error"
      x-swagger-router-controller: "Newsletter"
definitions:
  SignedMessage:
    required:
    - "message"
    - "signature"
    properties:
      message:
        type: "string"
      signature:
        type: "string"
    example:
      signature: "signature"
      message: "message"
  CertifiedTransferRequest:
    required:
    - "fee"
    - "from"
    - "signature"
    - "timestamp"
    - "to"
    - "value"
    properties:
      from:
        type: "string"
      to:
        type: "string"
      value:
        type: "integer"
      fee:
        type: "integer"
      timestamp:
        type: "integer"
      signature:
        type: "string"
    example:
      signature: "signature"
      fee: 6
      from: "from"
      to: "to"
      value: 0
      timestamp: 1
  CertifiedTransferResponse:
    required:
    - "message"
    - "txHash"
    properties:
      message:
        type: "string"
      txHash:
        type: "string"
    example:
      message: "message"
      txHash: "txHash"
  EncryptedPacket:
    required:
    - "encryptedPacket"
    - "version"
    properties:
      encryptedPacket:
        type: "string"
      version:
        type: "string"
    example:
      encryptedPacket: "encryptedPacket"
      version: "version"
  CertifiedTransfer:
    required:
    - "instructionPacket"
    - "signature"
    - "transfer"
    properties:
      transfer:
        $ref: "#/definitions/CertifiedTransferRequest"
      instructionPacket:
        $ref: "#/definitions/EncryptedPacket"
      signature:
        type: "string"
    example:
      instructionPacket:
        encryptedPacket: "encryptedPacket"
        version: "version"
      transfer:
        signature: "signature"
        fee: 6
        from: "from"
        to: "to"
        value: 0
        timestamp: 1
      signature: "signature"
  ETransferPacket:
    required:
    - "answer"
    - "email"
    - "question"
    properties:
      email:
        type: "string"
      question:
        type: "string"
      answer:
        type: "string"
      message:
        type: "string"
  eTransferCodeResponse:
    properties:
      code:
        type: "string"
      error:
        type: "string"
    example:
      code: "code"
      error: "error"
  BillPayeePacket:
    properties:
      payee:
        type: "string"
      accountNumber:
        type: "string"
  BrokerStatus:
    required:
    - "address"
    - "certifiedFee"
    properties:
      address:
        type: "string"
      certifiedFee:
        type: "integer"
    example:
      address: "address"
      certifiedFee: 0
  NewAccountReferal:
    required:
    - "newAccount"
    - "referrerId"
    properties:
      referrerId:
        type: "string"
      newAccount:
        type: "string"
    example:
      referrerId: "referrerId"
      newAccount: "newAccount"
  BoolResponse:
    type: "boolean"
    properties:
      success:
        type: "boolean"
    title: "A bool that to be returned indicating success/failure"
    example:
      success: true
  GoogleAuthUrl:
    required:
    - "url"
    properties:
      url:
        type: "string"
    example:
      url: "url"
  GoogleToken:
    required:
    - "token"
    properties:
      token:
        type: "string"
    example:
      token: "token"
  GooglePutRequest:
    required:
    - "token"
    - "wallet"
    - "walletName"
    properties:
      token:
        $ref: "#/definitions/GoogleToken"
      wallet:
        type: "string"
      walletName:
        type: "string"
    example:
      wallet: "wallet"
      walletName: "walletName"
      token:
        token: "token"
  GoogleFileIdent:
    required:
    - "id"
    properties:
      id:
        type: "string"
      name:
        type: "string"
      type:
        type: "string"
    example:
      name: "name"
      id: "id"
      type: "type"
  GoogleWalletItem:
    required:
    - "id"
    properties:
      id:
        $ref: "#/definitions/GoogleFileIdent"
      wallet:
        type: "string"
    example:
      wallet: "wallet"
      id:
        name: "name"
        id: "id"
        type: "type"
  GoogleListResult:
    required:
    - "wallets"
    properties:
      wallets:
        type: "array"
        items:
          $ref: "#/definitions/GoogleFileIdent"
    example:
      wallets:
      - name: "name"
        id: "id"
        type: "type"
      - name: "name"
        id: "id"
        type: "type"
  GoogleGetResult:
    required:
    - "wallets"
    properties:
      wallets:
        type: "array"
        items:
          $ref: "#/definitions/GoogleWalletItem"
    example:
      wallets:
      - wallet: "wallet"
        id:
          name: "name"
          id: "id"
          type: "type"
      - wallet: "wallet"
        id:
          name: "name"
          id: "id"
          type: "type"
  SubscriptionDetails:
    properties:
      id:
        type: "string"
      email:
        type: "string"
      confirmed:
        type: "boolean"
      firstName:
        type: "string"
      lastName:
        type: "string"
      country:
        type: "string"
      city:
        type: "string"
    example:
      firstName: "firstName"
      lastName: "lastName"
      country: "country"
      city: "city"
      id: "id"
      confirmed: true
      email: "email"
